# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: brewlog_dev
  pool: 5
  timeout: 5000

staging:
  adapter: postgresql
  encoding: unicode
  database: staging
  pool: 5
  timeout: 8000

production:
  adapter: postgresql
  database: production
  pool: 5
  timeout: 8000
